from multiproject.project.admin.admintemplateprovider import *
from multiproject.project.admin.basics import *
from multiproject.project.admin.categories import *
from multiproject.project.admin.projectrelations import *
from multiproject.project.admin.storages import *
from multiproject.project.admin.system import *
from multiproject.project.admin.project_icon import *
from multiproject.project.admin.news_forum import *
from multiproject.project.admin.protocols import ProtocolAdminPanel
from multiproject.project.admin.backup import BackupRestoreModule
