#!/usr/bin/env python
# coding: utf-8
LIST__URLS = [ 
"/", 
"discussion/",
"wiki",
"user?goto=https://localhost:4433/home/",
"wiki/TracRoadmap",
"admin",
"admin/discussion/forum",
"admin/discussion/group",
"admin/general/announcements",
"admin/general/backup",
"admin/general/categorization",
"admin/general/permissions",
"admin/general/protocol",
"admin/general/storages",
"admin/general/system",
"admin/ticket/components",
"admin/ticket/customfields",
"admin/ticket/milestones",
"admin/ticket/priority",
"admin/ticket/resolution",
"admin/ticket/severity",
"admin/ticket/type",
"admin/ticket/versions",
"admin/versioncontrol/repository",
"browser",
"discussion/forum/1",
"discussion/forum/1?order=lastreply&rowsperpage=20",
"discussion/topic/1",
"files",
"files/downloads",
"query",
"query?status=accepted&status=assigned&status=new&status=reopened&group=owner&col=id&col=summary&col=status&col=owner&col=type&col=priority&col=time&order=id",
"query?status=accepted&status=assigned&status=new&status=reopened&group=owner&col=id&col=summary&col=status&col=owner&col=type&col=priority&col=time&order=priority",
"roadmap?",
"roadmap",
"roadmap?show=completed",
"roadmap?show=completed&show=noduedate",
"roadmap?show=noduedate",
"search",
"timeline",
"timeline?from=04%2F29%2F13&daysback=30&authors=&wiki=on&discussion=on&ticket=on&files_events=on&files_downloads_events=on&changeset=on&milestone=on&update=Update",
"wiki",
"wiki/Downloads",
"wiki/RecentChanges",
"wiki/TitleIndex",
"wiki/TitleIndex?action=diff&version=1",
"wiki/TitleIndex?action=diff&version=1&old_version=0",
"wiki/TitleIndex?action=history",
"wiki/WikiStart",
]


# vim: sw=4

