from multiproject.common.admin.admintemplateprovider import HomeAdminTemplateProvider
from multiproject.common.admin.categories import CategoriesJSONRequestHandler
from multiproject.common.admin.permissions import PermissionsAdminPanel
