from multiproject.common.admin.admintemplateprovider import HomeAdminTemplateProvider
from multiproject.common.admin.grouppermissions import GroupPermissionAdminPanel
from multiproject.common.admin.usergroups import UserGroupsAdminPanel
from multiproject.common.admin.categories import CategoriesJSONRequestHandler
